CREATE TABLE IDPW(
    ID VARCHAR2(10) PRIMARY KEY,
    PW VARCHAR2(10) NOT NULL
);

INSERT INTO IDPW VALUES('admin', 'admin');
INSERT INTO IDPW VALUES('user', 'user');

CREATE TABLE MENU(
    FOOD_ID NUMBER PRIMARY KEY,
    FOOD_NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_FOOD_ID
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO MENU
VALUES (SEQ_FOOD_ID.NEXTVAL, 'HAMBURGER', 1000);
INSERT INTO MENU
VALUES (SEQ_FOOD_ID.NEXTVAL, 'PHOTATO', 600);
INSERT INTO MENU
VALUES (SEQ_FOOD_ID.NEXTVAL, 'COLA', 500);


CREATE TABLE ORDER_NUM(
    NUM NUMBER PRIMARY KEY,
    PRICE NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_ORDER_NUM
START WITH 3000
INCREMENT BY 1
NOCYCLE
NOCACHE;

CREATE TABLE ORDER_SUB(
    NUM NUMBER REFERENCES ORDER_NUM,
    FOOD_NAME VARCHAR2(20) NOT NULL,
    COUNT NUMBER NOT NULL
);

CREATE TABLE REVIEW(
    NUM NUMBER PRIMARY KEY,
    ID VARCHAR2(10) REFERENCES IDPW,
    CONTENT VARCHAR2(500) NOT NULL
);



CREATE SEQUENCE SEQ_REVIEW_NUM
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

INSERT INTO IDPW VALUES ('ryan', 'ryan');
INSERT INTO IDPW VALUES ('balm', 'balm');

